# Generated by Django 5.1.3 on 2026-08-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameplayer_is_busted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cardlocation',
            constraint=models.CheckConstraint(condition=models.Q(('zone_type__in', ['deck', 'line', 'discard'])), name='cardlocation_valid_zone'),
        ),
        migrations.AddConstraint(
            model_name='cardlocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('zone_type', 'line'), ('owner_player__isnull', False)), models.Q(('zone_type__in', ['deck', 'discard']), ('owner_player__isnull', True)), _connector='OR'), name='cardlocation_owner_zone_consistency'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='uniq_game_player_membership'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'seat_number'), name='uniq_game_seat_number'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gt', 0)), name='gameplayer_seat_positive'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.game'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='game.player'),
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='uniq_result_game_player'),
        ),
    ]
