# Generated by Django 5.1.3 on 2026-08-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameresult_alter_gameplayer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='target_score',
            field=models.IntegerField(default=200),
        ),
    ]
